name: Generate Snake Contribution Grid

on:
  schedule:  # Runs at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake SVG
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: nimsarac
          outputs: dist/snake.svg

      # Step 3: Commit and Push the Generated Snake SVG
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated Snake Animation"
          file_pattern: dist/snake.svg
